### ISSUE TITLE
Unexpected error, Undefined variable, and Argument issue

### ISSUE THREAD

**Issue by olafgrabienski** [backdrop-contrib/field_wrappers#1]
After installing and enabling the Field Wrappers module and visiting a "Manage display" page, most frontend pages and posts on my test site were broken. Apart from the title, the "Submitted by" line and the site name, there was only a white page with the message: "The website encountered an unexpected error. Please try again later."

In the DBlog I saw messages like these:

- Notice: Undefined variable: title_attributes in include() (line 51 of /(...)/modules/field_wrappers-1.x-1.x/templates/field.tpl.php).
- TypeError: Argument 1 passed to backdrop_attributes() must be of the type array, null given, called in /(...)modules/field_wrappers-1.x-1.x/templates/field.tpl.php on line 51 in backdrop_attributes() (line 2714 of /var/www/OGrabiensk/htdocs/backdrop-test-1-8/core/includes/common.inc).

I'm not sure if it's directly related but I've also noticed that most field wrappers on some displays (e.g. `admin/structure/types/manage/post/display/teaser`) were set to "None". In my opinion, they should be set to "Use default" by default.

When I disabled the module, everything was fine again. After enabling it once more, it was still fine but after visiting `admin/structure/types/manage/post/display/teaser` and changing a wrapper of the "Tags" field, the above mentioned error occured again.

**Comment by laryn** [comment]
Thanks @olafgrabienski I'll try to address this.

**Comment by laryn** [comment]
@olafgrabienski If you're interested to test again, I finally got back to this and pushed up some changes today.

**Comment by laryn** [comment]
Reopen if you still find a problem -- I think we're all set.

**Comment by olafgrabienski** [comment]
@laryn - thanks for addressing the issue(s)! I've tested the module again:

- √ Pages and posts of my test site are displayed correctly, with or without having changed field wrappers.
- √ Changing field wrappers leads to expected results.
- There is still one notice in DBlog, fired for every page view: `Undefined variable: title_attributes in include() (line 51 of /(...)/modules/field_wrappers-1.x-1.x/templates/field.tpl.php).`

**Comment by laryn** [comment]
@olafgrabienski I rebuild the field template file from the latest Backdrop core version. This line tipped me off that there may be some old cruft in the file 😄 :

> $Id: field.tpl.php,v 1.13 2010/03/26 17:14:45 dries Exp $

Are you willing to test this again? And (preferably, actually) test the new branch which has an additional dependency, FYI:

https://github.com/backdrop-contrib/field_wrappers/tree/1.x-1.x-issue2

**Comment by olafgrabienski** [comment]
@laryn Will do, probably by end of this week.

**Comment by olafgrabienski** [comment]
@laryn, I've installed the [new branch](https://github.com/backdrop-contrib/field_wrappers/tree/1.x-1.x-issue2) of *Field Wrappers* including *Field Formatter Settings* as a dependency. It works partially but I've also encountered some issues:

On the *Teaser* display (Customized for Post), I've got 2 notices:

> Undefined index: field_wrappers in field_wrappers_field_formatter_settings_summary_alter() (line 33 of /(...)/modules/field_wrappers-1.x-1.x-issue2/field_wrappers.module).
> Undefined index: field_wrappers in field_wrappers_field_formatter_settings_summary_alter() (line 37 of /(...)/modules/field_wrappers-1.x-1.x-issue2/field_wrappers.module).

On the *Default* display there weren't any notices.

I've also quickly tested the functionality on the Default display. As an example I changed the wrappers of *Tags*:
- Field wrapper: STRONG, Label wrapper: EM, Item wrapper: SPAN => works fine
- Item wrapper: None => doesn't work, showed same result as "Use Default"

One last observation for the moment: At fields with other visible display setting information (e.g. the Image field), I didn't see the information "Field wrappers: default" next to the *Configure* button.

**Comment by laryn** [comment]
@olafgrabienski 
I'm using the other branch as the default now and I think ready for a release. Care to test one more time? My thought was that we don't need to show the settings if they are default.

**Comment by olafgrabienski** [comment]
@laryn Yes, I can test it. Don't have time over the weekend, but next week, I guess.

**Comment by olafgrabienski** [comment]
@laryn I've finally tested the default branch:

- √ The notices mentioned in https://github.com/backdrop-contrib/field_wrappers/issues/1#issuecomment-464671376 are disappeared.
- √ The setting "Item wrapper: None" is working now!

---

>> At fields with other visible display setting information (e.g. the Image field), I didn't see the information "Field wrappers: default" next to the Configure button.

> My thought was that we don't need to show the settings if they are default.

I agree, it looks a bit inconsistent, as the use of default settings is mentioned at fields where there are no other settings, but I'm fine with that.

---

There's one new issue (or I didn't notice it last time): The image of the *Configure* button is not displayed. Looking at the `src` of the `field_image_formatter_settings_edit` input element with the browser inspector I see:

`http://example.com/misc/configure.png`

Should be:

`http://example.com/core/misc/configure.png`

**Comment by laryn** [comment]
Thanks @olafgrabienski! Closing this issue and have opened another for the configure image issue just to try to keep things separated a bit.
