### ISSUE TITLE
Consider adding an example hook function into an api.php file or Readme or Wiki

### ISSUE THREAD

**Issue by yorkshire-pudding** [backdrop-contrib/field_wrappers#10]
I've created a module in one site to add additional elements and then was needing to create one in another and couldn't get it to work.  I looked for documentation but none, and then remembered I'd done it before so was able to reference that.

I'm happy to add something but a steer over where to put it would be appreciated, and if Wiki, that would need to be activated.

**Comment by laryn** [comment]
Sounds great! I think an API file would be great, but also open to using the Wiki. Unfortunately I don't currently have the level of permissions needed to open that up. I'll post on Zulip.

**Comment by klonos** [comment]
Fixed @laryn :)

**Comment by yorkshire-pudding** [comment]
I've added a PR for the api.php file.  Happy to also add to the wiki once activated as I think there is merit in both approaches; api.php for when someone is looking at the module in their code editor and wiki for when they're looking at the module issue queue.

**Comment by laryn** [comment]
Thanks @yorkshire-pudding (and @klonos). I've merged the API file and opened up the Wiki as well.
