### ISSUE TITLE
Warnings appear on pseudo fields if this module is enabled.

### ISSUE THREAD

**Issue by yorkshire-pudding** [backdrop-contrib/field_wrappers#12]
See https://github.com/backdrop-contrib/realname/issues/4 for background as to why this needs solving here and in particular the recommendation from @indigoxela at https://github.com/backdrop-contrib/realname/issues/4#issuecomment-1868922168

**Steps to reproduce**

1. Install Field Wrappers and Real Name modules
2. Setup Real Name as per instructions
3. Visit account page

**Expected result**
Page loads with no errors

**Actual result**
Page loads with warnings - this image is from site with Devel enabled - it takes longer as it tries to build the backtrace array.
![image](https://github.com/backdrop-contrib/field_wrappers/assets/20357797/e1e1727d-27ce-43c2-971c-ea045c647838)

If Field Wrappers is disabled then the account page loads with no warnings.

**Comment by yorkshire-pudding** [comment]
@laryn - any ideas how to fix?

**Comment by laryn** [comment]
@yorkshire-pudding From what I've read in the comments, @indigoxela's suggestion sounds reasonable. I haven't had time to actually look into the code yet. If you get to a PR before I do I'll try to test, otherwise I'll let you know as soon as I have a chance to look at it and you can test.

**Comment by yorkshire-pudding** [comment]
@laryn - I've had a look at the code and tried sticking a few `dpm()` statements to understand what is going on, but I'm not sure at all how best to fix this.

**Comment by argiepiano** [comment]
What I would suggest here is to do a `field_info_field()` within `field_wrappers_preprocess_field()` and check if it's empty. If it is, then skip the wrapping.

Pseudo fields can't be configured in Manage display, therefore I believe it's best to bail out and not wrap pseudo fields at all.

**Comment by argiepiano** [comment]
Here's a PR #13. It skips wrapping if the "field" doesn't have field info (i.e. pseudo fields)

**Comment by yorkshire-pudding** [comment]
Thanks @argiepiano - I have tested and this works for me. In reference to the conversation in the Real Name issue, I confirmed that I could also use a `field--realname.tpl.php` file without issue.

LGTM.

**Comment by argiepiano** [comment]
Modified for a slightly more efficient way.

**Comment by yorkshire-pudding** [comment]
Tested the revised PR and still works.

LGTM

**Comment by laryn** [comment]
Thanks to @argiepiano for the fix, to @yorkshire-pudding for filing the issue and testing, and to @indigoxela for the input in the `realname` queue.
