### ISSUE TITLE
Add ability to add a class to the outer wrapper

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/field_wrappers#6]
Per a [Zulip conversation](https://backdrop.zulipchat.com/#narrow/stream/218635-Backdrop/topic/Node.20field.20classes/near/194229557), it would be nice to be able to specify a class for the outer wrapper.

**Comment by olafgrabienski** [comment]
Great idea! I'm interested in this functionality. Looking forward to test it, if you ever get a chance to add it!

**Comment by laryn** [comment]
Per the conversation linked above, this would basically incorporate functionality from https://www.drupal.org/project/field_formatter_class into this module.

I do still plan to do this, just don't have it scheduled yet.

**Comment by laryn** [comment]
@olafgrabienski Are you able to test https://github.com/backdrop-contrib/field_wrappers/commit/dbbce6b90e3877c072bbeb419084e1c966a8694d ?

**Comment by olafgrabienski** [comment]
Just tested, works generally fine and looks *very* useful (it's even possible to use tokens).

When hitting the "Configure" button of a field display, i got this PHP notice:

> Undefined index: field_wrapper_class in field_wrappers_field_formatter_settings_form_alter() (line 77 of /[...])/modules/field_wrappers/field_wrappers.module).

Also, I had the vague impression that saving the display settings was quite slow. Not sure, maybe it was a temporary issue with the test site.

**Comment by laryn** [comment]
Thanks @olafgrabienski I've made a new commit to fix the undefined index. 

I am not sure what to make of the second comment -- do you have any further info on that?

**Comment by olafgrabienski** [comment]
@laryn Thanks for the update! The fix works for me.

Please ignore my 2nd comment. It turned out that the whole test site got a bit slow in the meantime (it's quite old and packed with a lot of modules and experimental configurations).

**Comment by laryn** [comment]
@olafgrabienski What do you think of burying the Token info in a fieldset? I'm trying to decide if it's worth it or makes things any cleaner for general use.

![Screen Shot 2020-06-15 at 12 21 12 PM](https://user-images.githubusercontent.com/871421/84687212-f4330080-af02-11ea-9eda-0bb9cb20c91e.jpg)

vs.

![Screen Shot 2020-06-15 at 12 22 15 PM](https://user-images.githubusercontent.com/871421/84687219-fa28e180-af02-11ea-8cec-0b42078d4989.jpg)

**Comment by olafgrabienski** [comment]
@laryn Either way looks fine to me. Or what about the *Browse available tokens* link? See e.g. `admin/structure/types/manage/post > URL alias pattern`.

**Comment by laryn** [comment]
@olafgrabienski Ah, great -- I like that better.

![Screen Shot 2020-06-15 at 12 50 22 PM](https://user-images.githubusercontent.com/871421/84689600-d5366d80-af06-11ea-80c8-9e09bbb4c51b.jpg)
